version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - pg_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

volumes:
  pg_data:

networks:
  pg_network:
